tasks:
  generator_task:
    description: >
      Think critically about the user's input ```{query}```. Based on your perspective and your role,
      determine what you can message back. Perspective: ```{perspective}```
    expected_output: >
      Freely express your thoughts. Act as a friend to the user, helping them in a
      way that expresses your perspective.

  refiner_task:
    description: >
      Think critically about the coworker's output ```{initial}```. Determine areas of weakness in the
      output compared to ```{perspective}``` and keep them in mind.
    expected_output: >
      Improve and polish the output addressing weaknesses in order to make the output
      more relative to the perspective. An improvement is not required if the output is already perfect.

  conversationalist_task:
    description: >
      Respond concisely like a text message.Think critically about which aspect of your coworker's output
      is truly vital/important to user's input ```{query}```. Here is your coworker's output ```{second}```
    expected_output: >
      MAKE SURE THE RESPONSE IS 1-3 SENTENCES!! You may respond with a statement expressing your feelings/ideas, 
      followed by a statement seeking further user input or clarifying ideas. If you need clarification, 
      you may simply ask a question without an initial statement. Your ouput should be conversational and in
      first person. Make sure each sentence is straightforward and easily readable.
